version: '3.6'
networks:
  default:
    name: retail-sales-etl-network
    external: true
services:
  magic:
    image: onubrooks/${PROJECT_NAME}-mage:latest
    container_name: ${PROJECT_NAME}-mage
    networks:
      - default
    command: mage start ${PROJECT_NAME}
    env_file:
      - .env
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      USER_CODE_PATH: /home/src/${PROJECT_NAME}
      POSTGRES_DBNAME: ${POSTGRES_DBNAME}
      POSTGRES_SCHEMA: ${POSTGRES_SCHEMA}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_HOST: ${POSTGRES_HOST}
      POSTGRES_PORT: ${POSTGRES_PORT}
    ports:
      - 6789:6789
    # volumes:
    #   - .:/home/src/
    restart: on-failure:5
  postgres:
    image: onubrooks/postgres:latest
    restart: on-failure
    container_name: ${PROJECT_NAME}-postgres
    env_file:
      - .env
    build:
      context: .
      dockerfile: pg.Dockerfile
    environment:
      POSTGRES_DB: ${POSTGRES_DBNAME}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "${POSTGRES_PORT}:5432"


